### ISSUE TITLE
Unable to exit properly

### ISSUE THREAD

**Issue by NNRepos** [Arpan-206/EncryptoCLI#19]
i think there should be at least one of the following 2 ways to exit the program during execution:
1. hitting ctrl+C 
2. hitting enter on an "exit" option, e.g.:
```text
What do you want to do?  (Use arrow keys)
   ---------------
 ❯ Hash
   Encrypt
   Decrypt
   Exit
```
when hitting ctrl+C, we get an annoying error message:
```text
Cancelled by user

Traceback (most recent call last):
  File "C:\Users\nivim\code\python\EncryptoCLI\main.py", line 30, in <module>
    operation = prompt([
KeyError: 'operation'
```

i would like to add both options, or whichever one you prefer @Arpan-206 .
please let me know :)

**Comment by Arpan-206** [comment]
Go right ahead!
